manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: fkmg
      url-base: git@github.com:marcrickenbach

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.0.0-rc1
      import:
        name-allowlist:
          - hal_nxp
          - hal_stm32
          - cmsis
    - name: dac7578
      url: https://github.com/marcrickenbach/dac7578
      revision: main
      path: modules/fkmg/dac7578